/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/**/*.{js,jsx,ts,tsx}",
        "./index.html",
    ],
    darkMode: 'class',
    theme: {
        extend: {
            animation: {
                'fade-in': 'fadeIn 0.3s ease-out',
                'slide-up': 'slideUp 0.3s ease-out',
                'slide-down': 'slideDown 0.3s ease-out',
                'scale-in': 'scaleIn 0.2s ease-out',
                'shimmer': 'shimmer 2s infinite',
                'glow': 'glow 2s ease-in-out infinite alternate',
                'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
                'bounce-slight': 'bounceSlight 1s ease-in-out infinite',
                'glitch': 'glitch 1s infinite',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                slideUp: {
                    '0%': { transform: 'translateY(20px)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                slideDown: {
                    '0%': { transform: 'translateY(-20px)', opacity: '0' },
                    '100%': { transform: 'translateY(0)', opacity: '1' },
                },
                scaleIn: {
                    '0%': { transform: 'scale(0.95)', opacity: '0' },
                    '100%': { transform: 'scale(1)', opacity: '1' },
                },
                shimmer: {
                    '0%': { backgroundPosition: '-200% 0' },
                    '100%': { backgroundPosition: '200% 0' },
                },
                glow: {
                    '0%': { boxShadow: '0 0 5px rgba(239,68,68,0.5), 0 0 10px rgba(239,68,68,0.3)' },
                    '100%': { boxShadow: '0 0 20px rgba(239,68,68,0.8), 0 0 30px rgba(239,68,68,0.5)' },
                },
                bounceSlight: {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-5px)' },
                },
                glitch: {
                    '0%, 100%': { transform: 'translate(0)' },
                    '20%': { transform: 'translate(-2px, 2px)' },
                    '40%': { transform: 'translate(-2px, -2px)' },
                    '60%': { transform: 'translate(2px, 2px)' },
                    '80%': { transform: 'translate(2px, -2px)' },
                },
            },
            colors: {
                // Neon Cyberpunk Theme
                neon: {
                    red: '#ef4444',
                    redLight: '#f87171',
                    redDark: '#dc2626',
                    gold: '#f59e0b',
                    goldLight: '#fbbf24',
                    goldDark: '#d97706',
                    cyan: '#06b6d4',
                    cyanLight: '#22d3ee',
                    purple: '#a855f7',
                    purpleLight: '#c084fc',
                    green: '#22c55e',
                    greenLight: '#4ade80',
                },
                dark: {
                    950: '#030712',
                    900: '#0a0a0a',
                    800: '#111111',
                    700: '#1a1a1a',
                    600: '#262626',
                    500: '#404040',
                    400: '#525252',
                    300: '#737373',
                    200: '#a3a3a3',
                    100: '#d4d4d4',
                    50: '#ededed',
                },
                surface: {
                    DEFAULT: '#0a0a0a',
                    card: '#111111',
                    cardHover: '#1a1a1a',
                    muted: '#1a1a1a',
                    border: '#262626',
                    borderLight: '#333333',
                },
                tx: {
                    primary: '#ffffff',
                    secondary: '#a3a3a3',
                    muted: '#525252',
                    inverse: '#0a0a0a',
                    gold: '#f59e0b',
                    neonRed: '#ef4444',
                    neonCyan: '#06b6d4',
                },
                brand: {
                    50: '#fef2f2',
                    100: '#fee2e2',
                    200: '#fecaca',
                    300: '#fca5a5',
                    400: '#f87171',
                    500: '#ef4444',
                    600: '#dc2626',
                    700: '#b91c1c',
                    800: '#991b1b',
                    900: '#7f1d1d',
                },
            },
            fontFamily: {
                sans: ['Outfit', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
                display: ['Orbitron', 'Outfit', 'sans-serif'],
            },
            borderRadius: {
                '2xl': '1rem',
                '3xl': '1.5rem',
                'xl': '0.75rem',
            },
            boxShadow: {
                'glow-sm': '0 0 10px rgba(239,68,68,0.3)',
                'glow': '0 0 20px rgba(239,68,68,0.5)',
                'glow-lg': '0 0 30px rgba(239,68,68,0.7)',
                'glow-gold': '0 0 20px rgba(245,158,11,0.5)',
                'glow-cyan': '0 0 20px rgba(6,182,212,0.5)',
                'card': '0 4px 20px rgba(0,0,0,0.4)',
                'card-hover': '0 8px 30px rgba(239,68,68,0.2)',
                'inner-glow': 'inset 0 0 20px rgba(239,68,68,0.1)',
            },
            backgroundImage: {
                'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
                'grid-pattern': 'linear-gradient(to right, rgba(255,255,255,0.03) 1px, transparent 1px), linear-gradient(to bottom, rgba(255,255,255,0.03) 1px, transparent 1px)',
            },
        },
    },
    plugins: [],
};